appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WTxLrGDqVaZRCXtczTscVg7hPn++SMl1LVIOB1loVOueCNaVcUQupI+EXh7GRg2hyk+rLqaspyGfspF3XJvNRK+6Yio6w7+opyDJGfQsoFcRkat6Shw0Y1xj372b2O5c0plSSCG+Fb5DzwEIi5g11MWrSkoe6+41I+LE3kz+QB9PHWuLUHpOv5MJkxWNulxObbuzbm3AmEdcNXtUFH1uL6vLlD+HRWSANhqCDYI5SPNEtb1IrVFJTn9W7o7IVV8DWQtVbF+YPyriPWNHcPCLctm3lN+FbVU2846RfMkB8MWCnzPOTPccNXYc9+y4zgQ37aR6mbxNwyZxft9eg5Up1AtgA1GN+DsKs8deRjVSE4nhnxjP/Pr+oVOjZs8JWOFuuvgWg3gd7S6y7G5/Cama1qpo+vmzlbjec9TOkWCtT1Sq4sBCkdlo7MsoTPxIBeOVGQn4w4m2TCSjiBfnbVtWmOq2KeoNOLof2ojPq5p1bhMa9Z1QTyk3sI8baWoYKQanhrFf3PyJX0gFQ5iHFOuWRV+i5n8Xp3/50nKULcX8k9YLJHb5AuTNwkAxyI8bHTem5jDyy5OK9c4OecFsa+8ur9tH8dIyMTHAwaHgvCGcxniIMnUsfrQc8KQ4e87PK9M1f6VmrTIRKLItr215BxxEUOvRFdvLY5QKcUAQmmGn4yY=}
bot:
  automerge: true
